BookStore.Web/Models/Admin/AdminTabEnums.cs
namespace BookStore.Web.Models.Admin
{
    public enum AdminTabs
    {
        UsersManagement   
    }

    public enum UserRoles
    {
        Customer,
        Admin
    }
}

BookStore.Web/Models/Admin/AdminTabsViewModel.cs
namespace BookStore.Web.Models.Admin
{
    public class AdminTabsViewModel
    {
        public AdminTabsViewModel(AdminTabs adminTab)
        {
            ActiveAdminTab = adminTab;
        }

        public AdminTabs ActiveAdminTab { get; }
    }
}

BookStore.Web/Models/Admin/IAdminTabViewModel.cs
namespace BookStore.Web.Models.Admin
{
    interface IAdminTabViewModel
    {
        public AdminTabsViewModel AdminTabsViewModel { get; }
    }
}

BookStore.Web/Models/Admin/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using BookStore.Web.Validation;

namespace BookStore.Web.Models.Admin
{
    public class User
    {
        public string Id { get; set; }

        [Required]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed")]
        public string UserName { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [ValidUserRole]
        public IList<string> Roles { get; set; }

    }
}

BookStore.Web/Models/Admin/UsersManagementViewModel.cs
using System.Collections.Generic;

namespace BookStore.Web.Models.Admin
{
    public class UsersManagementViewModel : IAdminTabViewModel
    {
        public UsersManagementViewModel(IList<User> users)
        {
            Users = users;
            AdminTabsViewModel = new AdminTabsViewModel(AdminTabs.UsersManagement);
        }

        public AdminTabsViewModel AdminTabsViewModel { get; }

        public IList<User> Users { get; }
    }
}

BookStore.Web/Models/Book/BookCardViewModel.cs
namespace BookStore.Web.Models.Book
{
    public class BookCardViewModel
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public int Price { get; set; }

        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
    }
}

BookStore.Web/Models/Book/BookDetailViewModel.cs
namespace BookStore.Web.Models.Book
{
    public class BookDetailViewModel
    {
        public string Title { get; set; }
        public string Summary { get; set; }
        public int Price { get; set; }

        public string AuthorName { get; set; }
    }
}

BookStore.Web/Models/ErrorViewModel.cs
namespace BookStore.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookStore.Web/Controllers/AdminController.cs
using System.Threading.Tasks;
using BookStore.Web.Models.Admin;
using BookStore.Web.Repository;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IUserRepository _userRepository;

        public AdminController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Index() {
            return RedirectToAction(nameof(UsersManagement));
        }

        public async Task<IActionResult> UsersManagement()
        {
            var users = await _userRepository.GetAll();
            return View(new UsersManagementViewModel(users));
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userRepository.Get(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser([FromForm] User user)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(nameof(user));
            }

            await _userRepository.Update(user);

            return RedirectToAction(nameof(UsersManagement));
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            await _userRepository.Delete(id);

            return RedirectToAction(nameof(UsersManagement));
        }
    }
}

BookStore.Web/Controllers/BookController.cs
using System.Threading.Tasks;
using BookStore.Web.Models.Book;
using BookStore.Web.Repository;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public async Task<IActionResult> Detail(int id)
        {
            var book = await _bookRepository.Get(id);

            if (book == null)
            {
                return NotFound();
            }

            var viewModel = new BookDetailViewModel
            {
                Title = book.Title,
                Summary = book.Summary,
                Price = book.Price,
                AuthorName = $"{book.Author.LastName}, {book.Author.FirstName}"
            };

            return View(viewModel);
        }
    }
}

BookStore.Web/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BookStore.Web.Models;
using BookStore.Web.Models.Book;
using BookStore.Web.Repository;

namespace BookStore.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBookRepository _bookRepository;

        public HomeController(ILogger<HomeController> logger, IBookRepository bookRepository)
        {
            _logger = logger;
            _bookRepository = bookRepository;
        }

        public async Task<IActionResult> Index()
        {
            var books = await _bookRepository.GetAll();

            var booksData = new List<BookCardViewModel>(books.Count);
            foreach (var book in books)
            {
                booksData.Add(new BookCardViewModel
                {
                    AuthorFirstName = book.Author.FirstName,
                    AuthorLastName = book.Author.LastName,
                    Summary = book.Summary,
                    Price = book.Price,
                    Title = book.Title,
                    BookId = book.Id
                });
            }

            ViewData["Books"] = booksData;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookStore.Web/Views/Admin/EditUser.cshtml
@model User

@{
    ViewData["Title"] = "Edit User Page";
}

<form asp-controller="Admin" asp-action="EditUser" method="POST">
    <div hidden class="form-group">
      <label asp-for="Id"></label>
      <input type="text" asp-for="Id" class="form-control" value="@Model.Id" />
    </div>

    <div class="form-group mt-3">
      <label asp-for="UserName">Username</label>
      <input type="text" asp-for="UserName" class="form-control" value="@Model.UserName" />
    </div>

    <div class="form-group">
      <label asp-for="Email">Email</label>
      <input type="text" asp-for="Email" class="form-control" value="@Model.Email" />
    </div>

    <div class="form-group">
        <label asp-for="Roles">Roles</label>
        <div>
            <select class="user-roles" multiple asp-for="Roles">
                @foreach (var role in Enum.GetNames(typeof(UserRoles)))
                {
                    @if (Model.Roles.Contains(role))
                    {
                        <option value="@role" selected="">@role</option>
                    }
                    else
                    {
                        <option value="@role">@role</option>
                    }
                }
            </select>
        </div>        
    </div>
    
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Save</button>

      <a asp-controller="Admin" asp-action="UsersManagement" class="btn btn-secondary ml-3" role="button">Cancel</a>
    </div>
        
</form>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.user-roles').multiselect();
        });
    </script>
}

BookStore.Web/Views/Admin/UsersManagement.cshtml
@model BookStore.Web.Models.Admin.UsersManagementViewModel

@{
    ViewData["Title"] = "Admin Page";
}

<partial name="_AdminTabs.cshtml" model="@Model.AdminTabsViewModel" />

@* <ul class="nav nav-pills nav-stacked mt-3 hidden">
    <li class="nav-item">
        <button type="button" class="btn btn-primary">Button</button>
    </li>
</ul> *@

<table class="table mt-3">
    <thead>
        <tr>
            <th>User</th>
            <th>Email</th>
            <th>Role</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td scope="row">@user.UserName</td>
                <td>@user.Email</td>
                <td>@string.Join(", ", user.Roles)</td>               
                <td>
                    <a asp-controller="Admin" asp-action="EditUser" asp-route-id="@user.Id" class="btn btn-primary" role="button">Edit</a>
                    <a asp-controller="Admin" asp-action="DeleteUser" asp-route-id="@user.Id" class="btn btn-primary ml-1" role="button">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.user-roles').multiselect();
        });
    </script>
}

BookStore.Web/Views/Admin/_AdminTabs.cshtml
@using BookStore.Web.Models.Admin
<nav class="nav nav-tabs nav-stacked">
    <a class="nav-link @(Model.ActiveAdminTab == AdminTabs.UsersManagement ? "active" : "")" asp-controller="Admin" asp-action="Index">User Management</a>
    <a class="nav-link" href="#">Other</a>
</nav>

BookStore.Web/Views/Book/Detail.cshtml
@model BookStore.Web.Models.Book.BookDetailViewModel

@{
    ViewData["Title"] = "Book Detail";
}

<h1>@Model.Title</h1>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label asp-for="Title">Title</label>
        </dt>
        <dd class="col-sm-10">
            <input disabled="disabled" class="form-control" value="@Model.Title" />
        </dd>

        <dt class="col-sm-2">
            <label asp-for="Summary">Summary</label>
        </dt>
        <dd class="col-sm-10">
            <textarea disabled="disabled" class="form-control">@Model.Summary</textarea>
        </dd>

        <dt class="col-sm-2">
            <label asp-for="Price">Price (€)</label>
        </dt>
        <dd class="col-sm-10">
            <input disabled="disabled" class="form-control" value="@Model.Price" />
        </dd>

        <dt class="col-sm-2">
            <label asp-for="AuthorName">Author</label>
        </dt>
        <dd class="col-sm-10">
            <input disabled="disabled" class="form-control" value="@Model.AuthorName" />
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

BookStore.Web/Views/Book/_Books.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager

@model IList<BookCardViewModel>

<div class="card-deck">
    @foreach (var book in Model)
    {
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">@book.Title</h5>
                <h6 class="card-subtitle mb-2 text-muted">@book.AuthorLastName, @book.AuthorFirstName</h6>
                <p class="card-text">@book.Summary</p>
            </div>

            <div class="card-footer text-right">
                <span class="font-weight-bold align-middle">Price: </span>
                <span class="text-muted align-middle">@book.Price €</span>
                
                <a asp-controller="Book" asp-action="Detail" asp-route-id="@book.BookId" class="btn btn-primary ml-1 float-left">Details</a>

                @if (SignInManager.IsSignedIn(User) && User.IsInRole(UserRoles.Customer.ToString()))
                {
                    <button class="btn btn-primary ml-1">Buy</button>
                }
            </div>
        </div>
    }
</div>

BookStore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1 class="display-4">Welcome to the awesome book store</h1>

<partial name="~/Views/Book/_Books.cshtml" model="@ViewData["Books"]" />

BookStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-multiselect/dist/css/bootstrap-multiselect.css" type="text/css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li @(!User.IsInRole(UserRoles.Admin.ToString()) ? "hidden" : "") class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>